### ISSUE TITLE
Doesn't work with Micropython 1.11

### ISSUE THREAD

**Issue by vogt31337** [tkurbad/micropython-ili9341#1]
Hi,

I tried your lib on an ESP32, with MicroPython v1.11 on 2019-05-29; ESP32 module with ESP32, downloaded from their webpage.
It seems like they do not have activated decorators, the REPL console throws SyntaxError Exceptions on every decorator.

So if this lib needs a special version / config of MicroPython please provide documentation!

BR

**Comment by Josverl** [comment]
I think this is meant to use the nightly builds, rather than the latest stable ::
the `@micropython.viper` decorators work 
in [GENERIC-SPIRAM : esp32spiram-idf3-20191211-v1.11-633-gb310930db.bin](https://micropython.org/download#esp32)

but the two `@micropython.asm_thumb` still fail

**Comment by tkurbad** [comment]
This code is abandoned because it has several flaws. Feel free to fix or use other available options.
